### ISSUE TITLE
script attempts to change the value of a getter

### ISSUE THREAD

**Issue by kristianserrano** [kandashi/Active-Auras#302] opened 2023-11-25 22:21 UTC
**Describe the bug**
This line attempts to set a new value to `isSuppressed` which throws an error.
https://github.com/kandashi/Active-Auras/blob/5f3b00987a9955279e1f603a7d467fc0f5897fff/src/lib/AAHelpers.mjs#L375

Instead, it should perform an `update()` on the effect to change the value.
```js
await args[1].effect.update({'isSuppressed': true});
```

**To Reproduce**
1. Set an aura to ignore self
1. See error

**Expected behavior**
Set `isSuppressed`with an update on the effect normally

**Environment:**
 - OS: macOS
 - Browser: Chrome
 - Foundry Version: v11.315
 - Module Version: 0.9.0
 - All Modules Disabled: No
 - Module List if no: only content modules and those required by Active Auras.

**Additional context**
This is was observed in the SWADE system, but did not try it in any others.

**Comment by MrPrimate** [comment] 2023-11-26 08:39
Oh interesting, I think this is a product of the removal of Legacy Transferal in SWADE.

**Comment by MrPrimate** [comment] 2023-11-26 09:15
Fixed in v0.9.1

**Closed by MrPrimate** 2023-11-26 09:15 UTC

**Comment by MrPrimate** [comment] 2023-11-26 09:20
Duplicate of https://github.com/kandashi/Active-Auras/issues/295
